### ISSUE TITLE
Bug en el sistema de Votaciones.

### ISSUE THREAD

**Issue by scidroid** [scidroid/Carlos-el-botsito#1]
# Bug en el sistema de votaciones.
cuando alguien pone algo en el chat la variable no se suma, y al imprimir los resultados todos quedan en cero, específicamente en esta parte del código (Lineas 78-91)
```python
    if ctx.content.lower() == 1:
        uno =+ 1

    if ctx.content.lower() == 2:
        dos =+ 1

    if ctx.content.lower() == 3:
        tres =+ 1

    if ctx.content.lower() == 4:
        cuatro =+ 1

    if ctx.content.lower() == 5:
        cinco =+ 1
```

**Comment by christivn** [comment]
No he hecho clone del bot para comprobar como funciona, ¿has probado a comprobar los if en vez de con int con string?
```
if ctx.content.lower() == "1":
        uno =+ 1

if ctx.content.lower() == "2":
        dos =+ 1

if ctx.content.lower() == "3":
        tres =+ 1

if ctx.content.lower() == "4":
        cuatro =+ 1

if ctx.content.lower() == "5":
        cinco =+ 1
```

**Comment by scidroid** [comment]
> No he hecho clone del bot para comprobar como funciona, pero: ¿has probado a comprobar los if en vez de con int con string?
> 
> ```python
> if ctx.content.lower() == "1":
>         uno =+ 1
> 
> if ctx.content.lower() == "2":
>         dos =+ 1
> 
> if ctx.content.lower() == "3":
>         tres =+ 1
> 
> if ctx.content.lower() == "4":
>         cuatro =+ 1
> 
> if ctx.content.lower() == "5":
>         cinco =+ 1
> ```

esto funciono, he reparado el codigo y ahora me sale el siguiente error
```
Traceback (most recent call last):
  File "bot.py", line 52, in event_message
    uno += 1
UnboundLocalError: local variable 'uno' referenced before assignment
```
