### ISSUE TITLE
Bug con variables

### ISSUE THREAD

**Issue by scidroid** [scidroid/Carlos-el-botsito#2]
al ejecutar el codigo, da el siguiente codigo de error
```
Traceback (most recent call last):
  File "bot.py", line 52, in event_message
    uno += 1
UnboundLocalError: local variable 'uno' referenced before assignment
```
pero, ya se ha asignado la variable antes de escribir el codigo.
se puede evidenciar en el archivo `bot.py`.

**Comment by pythonBoy123** [comment]
tienes que escribir `global nombre de la variable que quieres usar dentro de la funcion` para evitar que salga ese error y que pueda aumentar el valor de uno
